# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
name: Tests

# Trigger the workflow's on pushed branches or commits to main branch.
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/workflows/*"
      - "!.github/workflows/test-package.yaml"
  push:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/workflows/*"
      - "!.github/workflows/test-package.yaml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
    tags:
      - "**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    strategy:
      # Keep running even if one job fails
      fail-fast: false
      matrix:
        python:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - uses: actions/checkout@v3

      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python }}"

      # preserve pip cache to speed up installation
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install
        run: |
          pip install --upgrade pip
          pip install .
          pip install --upgrade --pre -r dev-requirements.txt .
          pip freeze

      - name: Run tests
        run: pytest -v --color=yes --cov=ltiauthenticator ltiauthenticator/tests
